name: build and TEst mary branch
on:
  push:
    branches:
      - mary
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: temurin
      - name: test
        run: mvn test
      - name: package
        run: mvn clean package

      - name: login to docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.MY_USERNAME }}
          password: ${{ secrets.MY_PASSWORD }}


        
      - name: build and push docker
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: maryrani/stack1:1.1
